language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
# before_script:
# - psql -c 'create database "boilermaker-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  # - npm test # test the code
  - npm run build-client # make the bundle
# before_deploy:
#   - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy: # see README for details on these keys
  skip_cleanup: true
  provider: heroku
  app: your-agenda
  api_key:
    secure: Igk0fUU+2Gr72a7FuT+bq8+Z3GbrzePbMwOaFe+vhX6qDfMz9JMwNDs03m/FiQPxhrxLVM3B7z2r8VBTggVNXceuJx/i7XnxjepQGwbT61EK8Xc0X6GItcPfSCqnsKdR+mW1CdP8+MMauI+NW9IPEnyWu2qOAZMSKjcGA+XVUINze8ydLSYYtvdgqrLFJuRr4/h/2xakuaq5Vo/ZrTvqnUgN4Bg+pWSTtagNB6S1LYQoM0B7FnyBDTl98fDU9ntX1ytcjcZ6U6RTf6taeHU/9SkYhW8xWdnkx0vY+3N49glgsA0hpS8gcHtttMbR351cQB4aEz4iYYSTZoBgejQc3SlNCEWaRfODkDbTxJRRLsa3LjXmnOlqzLKsb7FMz4oJljN+MfUtOHdyojP/dv8Nwk9WcPbsxMao8clcfxWZqZ9Jmf6+/AXJYKRJMgPQe9aLplMvaLSY3fQdICmJ6Xg/cMQvMkPCCWj4iZ7hLPY6MM29OB+mWVEuoA1pB67uScrf3e8QIh3JJNK4oYHnLUykQF00rVSqEHf9+TgLKvRnKJvbjSABHzGkqBokmzaI7AjfnIWjwgfkdlJ4CkLU4hMiIvaNWgQz7V1hWfVXIkG3zgvVRhk2SWweRDZRmmYntTZoJqY8MhOxwAZNXLqvb0L2ksxDV2zGhK9tbdevLni936A=
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
